interface IQuizzCommentModel {
    id?: number;
    comment: string;
    postedDate?: Date;
    isDeleted?: boolean;

    authorId?: number;
    quizzId: number;

    // from query
    isQuizzmate?: boolean;
    authorUserName?: string;
    authorFullName?: string;
    authorProfilePixUrl?: string;

    numLikes?: number;
    isLiked?: boolean;

    numFlags?: number;
    isFlagged?: boolean;

    like?: IActionElement;
    flag?: IActionElement;

    tmpComment?: string;
    editMode?: boolean;
    editState?: IActionElement;

    // generated by code
    authorName?: string;
    canEdit?: boolean;
    isAuthor?: boolean;

    // for view
    isOpen?: boolean;
}