using L2L.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace L2L.WebApi.Models
{
    public class QuizzClassModel : WithAgeModel
    {
        public int Id { get; set; }
        public bool MembershipNeedsApproval { get; set; }
        public bool IsDeleted { get; set; }
        public string ClassName { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
        public int QuizzClassLessonIdx { get; set; }
        public string QuizzChatGuid { get; set; }

        // Foreign Keys
        public int TeacherId { get; set; }

        // Generated from query
        public bool IsTeacherQuizzmate { get; set; }
        public string TeacherUserName { get; set; }
        public string TeacherFullName { get; set; }
        public int NumStudents { get; set; }
        public int NumMaterials { get; set; }
        public int NumStudentJoinRequests { get; set; }
        public int NumNewInviteAccepts { get; set; }
        public string LatestAnnouncement { get; set; }
        public DateTime? LatestAnnouncementPosteDate { get; set; }
        public bool IsRequestSent { get; set; }
        public bool IsInviteSent { get; set; }
        public bool IsMember { get; set; }
        public int QuizzClassMemberId { get; set; }
        public QuizzClassMemberModel Member { get; set; }
        public int NumComments { get; set; }

        // Generate from code
        public bool IsTeacher { get; set; }
        public string TeacherName { get; set; }
        public int NumNewLessonItemCount { get; set; }

        // From Client

        // QzImageEditorModel
        public string ImageUrl { get; set; }
        public string ImageContent { get; set; }
        public string NewImageFileName { get; set; }
        public bool IsImageChanged { get; set; }
    }

    public class QuizzClassCommentModel : WithAgeModel
    {
        public int Id { get; set; }
        public DateTime PostedDate { get; set; }
        public string Comment { get; set; }
        public bool IsDeleted { get; set; }

        // Foreign Keys
        public int AuthorId { get; set; }
        public int QuizzClassId { get; set; }

        // Generated
        public bool IsQuizzmate { get; set; }
        public string AuthorName { get; set; }
        public string AuthorUserName { get; set; }
        public string AuthorFullName { get; set; }
        public string AuthorProfilePixUrl { get; set; }
        

        // generated by code
        public bool IsNew { get; set; }
        public bool IsAuthor { get; set; }
    }

    public class QuizzClassAnnouncementModel
    {
        public int Id { get; set; }
        public string Announcement { get; set; }
        public DateTime PostedDate { get; set; }

        // Foreign Keys
        public int QuizzClassId { get; set; }

        // generated by code
        public bool IsNew { get; set; }
    }

    public class QuizzClassQuizzModel
    {
        public int Id { get; set; }
        public DateTime PostedDate { get; set; }

        // Foreign Keys
        public int QuizzId { get; set; }
        public int QuizzClassId { get; set; }
    }

    #region Quizz Class Lesson
    public class QuizzClassLessonModel : WithAgeModel
    {
        public int Id { get; set; }
        public int QuizzClassLesssonIdx { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }

        // Foreign Keys
        public int QuizzClassId { get; set; }

        // Generated from query
        public string QuizzClassName { get; set; }
        public string QuizzClassDescription { get; set; }
        public string QuizzClassImageUrl { get; set; }
        public bool IsTeacherQuizzmate { get; set; }
        public int TeacherId { get; set; }
        public string TeacherUserName { get; set; }
        public string TeacherFullName { get; set; }
        public QuizzClassMemberModel Member { get; set; }
        public int NumComments { get; set; }

        // Generate from code
        public bool IsNew { get; set; }
        public bool IsTeacher { get; set; }
        public string TeacherName { get; set; }
        public int NewMaterialCount { get; set; }
        public int NewMessageCount { get; set; }
        public int NewCommentCount { get; set; }
        public int NewQuizzCount { get; set; }
    }

    public class QuizzClassLessonMessageModel : QzEditorModel
    {
        public int Id { get; set; }
        public DateTime PostedDate { get; set; }
        public string Message { get; set; }
        public bool IsDeleted { get; set; }

        // Foreign Keys
        public int QuizzClassLessonId { get; set; }

        // generated by Query
        public int QuizzClassId { get; set; }
        public int QuizzClassLessonIdx { get; set; }

        // generated from code
        public bool IsNew { get; set; }
    }

    public class QuizzClassLessonCommentModel : WithAgeModel
    {
        public int Id { get; set; }
        public DateTime PostedDate { get; set; }
        public string Comment { get; set; }
        public bool IsDeleted { get; set; }

        // Foreign Keys
        public int QuizzClassLessonId { get; set; }
        public int AuthorId { get; set; }

        // Generated from query
        public int QuizzClassId { get; set; }
        public int QuizzClassLessonIdx { get; set; }
        public string AuthorUserName { get; set; }
        public string AuthorFullName { get; set; }
        public string AuthorProfilePixUrl { get; set; }
        public bool IsQuizzmate { get; set; }
        public bool IsAuthor { get; set; }
        public bool IsTeacher { get; set; }

        // Generated from code
        public bool IsNew { get; set; }
        public string AuthorName { get; set; }
    }

    public class QuizzClassLessonQuizzModel
    {
        public int Id { get; set; }
        public DateTime PostedDate { get; set; }

        // Foreign Keys
        public int QuizzId { get; set; }
        public int QuizzClassId { get; set; }
        public int QuizzClassLessonId { get; set; }
    }
    #endregion

    #region Quizz Class Member
    public class QuizzClassMemberModel : WithAgeModel
    {
        public int Id { get; set; }
        public bool IsNew { get; set; }
        public bool IsNewInviteAccepted { get; set; }
        public bool HasNew { get; set; }
        public int NewChatCount { get; set; }
        public bool IsParent { get; set; }

        // *** Class
        public int NewClassCommentCount { get; set; }
        public int NewClassMaterialCount { get; set; }
        public int NewAnnouncementCount { get; set; }
        public int NewClassLesson { get; set; }
        public int NewClassQuizzCount { get; set; }

        // *** Lessons
        public string NewLessonMaterialCount { get; set; }
        public string NewLessonCommentCount { get; set; }
        public string NewLessonMessageCount { get; set; }
        public string NewLessonQuizzCount { get; set; }

        // Foreign Keys
        public int QuizzClassId { get; set; }
        public int StudentId { get; set; }
        public int? DependentId { get; set; }

        // Generated by query
        public bool IsQuizzmate { get; set; }
        public string StudentUserName { get; set; }
        public string StudentFullName { get; set; }
        public string StudentProfilePixUrl { get; set; }

        // generated by code
        public string StudentName { get; set; }
    }

    public class QuizzClassJoinRequestModel : WithAgeModel
    {
        public int Id { get; set; }
        public DateTime PostedDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsAccepted { get; set; }
        public bool IsNew { get; set; }
        public string Message { get; set; }

        // Foreign Keys
        public int QuizzClassId { get; set; }
        public int UserId { get; set; }

        // generated by query
        public bool IsQuizzmate { get; set; }
        public string UserUserName { get; set; }
        public string UserFullName { get; set; }
        public string UserProfilePixUrl { get; set; }

        // Generated by code
        public string UserName { get; set; }
    }

    public class QuizzClassInviteRequestModel
    {
        public int Id { get; set; }
        public DateTime PostedDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsAccepted { get; set; }
        public bool IsNew { get; set; }
        public string Message { get; set; }

        // Foreign Keys
        public int QuizzClassId { get; set; }
        public int UserId { get; set; }

        // generated by query
        public bool IsQuizzmate { get; set; }
        public string UserUserName { get; set; }
        public string UserFullName { get; set; }
        public DateTime UserBirthdate { get; set; }
        public string UserProfilePixUrl { get; set; }
        public string ClassName { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
        public string TeacherUserName { get; set; }
        public string TeacherFullName { get; set; }
        public DateTime TeacherBirthdate { get; set; }
        public string ImageUrl { get; set; }

        // Generated by code
        public string UserName { get; set; }
        public string TeacherName { get; set; }
        public int UserAge { get; set; }
        public int TeacherAge { get; set; }
    }
    #endregion

    #region Class Material
    public enum QuizzClassMaterialtypeEnum
    {
        Notes = 0,
        Quizz,
        File,
        Image,
        VideoUrl,
        WebsiteUrl
    }

    public class QuizzClassMaterialModel
    {
        public int Id { get; set; }
        public QuizzClassMaterialtypeEnum MaterialType { get; set; }
        public string Content { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }

        // Foreign Keys
        public int? QuizzId { get; set; }
        public int? QuizzClassLessonId { get; set; }
        public int QuizzClassId { get; set; }

        // Navigation Properties
        public Quizz Quizz { get; set; }
        public QuizzClassLessonModel QuizzClassLesson { get; set; }
        public QuizzClassModel QuizzClass { get; set; }
    }
    #endregion

    #region Chat
    public class QuizzClassChatModel
    {
        public int Id { get; set; }
        public DateTime PostedDate { get; set; }
        public string Message { get; set; }

        // Foreign Keys
        public int QuizzClassId { get; set; }
        public int AuthorId { get; set; }

        // Navigation Properties
        public QuizzClassModel QuizzClass { get; set; }
        public User Author { get; set; }
    }
    #endregion

    #region 
    #endregion
}