using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace L2L.WebApi.Models
{
    public enum QuizzMessageTypeEnum
    {
        Quizzmate,
    }

    public class QuizzmateMsgThreadModel
    {
        public int Id { get; set; }
        public bool IsGroupMsg { get; set; }
        public string GroupMessageName { get; set; }
        public string SignalRGroupName { get; set; }
        public bool IsDeleted { get; set; }

        // Foreign Keys

        // Navigation Properties
        public IList<QuizzmateMsgThreadMemberModel> MsgThreadMembers { get; set; }
        public IList<QuizzmateMsgModel> Messages { get; set; }

        // Generated from code
        public bool IsViewerOnly { get; set; }
    }

    public class QuizzmateMsgThreadMemberModel : WithAgeModel
    {
        public int Id { get; set; }
        public bool HasNew { get; set; }
        public int NewCount { get; set; }

        // Foreign Keys
        public int QuizzmateMsgThreadId { get; set; }
        public int UserId { get; set; }

        // Generated from query
        public string UserName { get; set; }
        public string UserFullName { get; set; }
        public string ProfileImageUrl { get; set; }
    }

    public class QuizzmateMsgModel
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public DateTime PostedDate { get; set; }

        // Foreign Keys
        public int AuthorId { get; set; }
        public int QuizzmateMsgThreadId { get; set; }

        // Generated
        public bool IsNew { get; set; }
        public string UserName { get; set; }
        public string ProfileImageUrl { get; set; }
    }

    public class QuizzConnectMsgThread
    {
        public bool IsEmpty { get; set; }
        public QuizzMessageTypeEnum QuizzMessageType { get; set; }
        // Last Message Id
        public int Id { get; set; }
        public int NewCount { get; set; }
        public string GroupName { get; set; }
        public int QuizzmateMsgThreadId { get; set; }

        // generated by Query
        public string LastSenderUserName { get; set; }
        public string LastSenderFullName { get; set; }
        public string LastSenderProfileUrl { get; set; }
        public string LastSenderMsg { get; set; }
        public DateTime LastMsgPostedDate { get; set; }

        // generated by code
        public string LastSenderName { get; set; }
    }
}