using L2L.Entities;
using L2L.Entities.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace L2L.WebApi.Models
{
    public class QuizzOverviewModel : ITrackableModel, IWithAgeModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsLive { get; set; }
        public int Category { get; set; }
        public QuizzDifficultyEnum Difficulty { get; set; }
        public QuizzGradeLevelEnum GradeLevelMin { get; set; }
        public QuizzGradeLevelEnum GradeLevelMax { get; set; }

        public bool IsBuiltIn { get; set; }
        public BuiltInTypeEnum BuiltInType { get; set; }
        public int MainType { get; set; }
        public int SubType { get; set; }
        public int SubType2 { get; set; }
        public int SubType3 { get; set; }
        public int SubType4 { get; set; }
        public int SubType5 { get; set; }
        public string QuizzTags { get; set; }

        // foreign keys
        public int OwnerId { get; set; }

        // generated from query
        public int NumQuestions { get; set; }
        public int NumQuickNotes { get; set; }
        public int NumLikes { get; set; }
        public int NumTaken { get; set; }

        public bool IsQuizzmate { get; set; }
        public string OwnerUserName { get; set; }
        public string OwnerFullName { get; set; }
        public int OwnerPoints { get; set; }
        public int TotalBadge { get; set; }
        public int ReviewerId { get; set; }
        public int TestId { get; set; }
        public bool IsBookmarked { get; set; }
        public bool IsLiked { get; set; }
        public int QuizzRatingId { get; set; }
        public int NumComments { get; set; }

        public DailyRewardModel DailyReward { get; set; }

        // generated from code
        public string OwnerName { get; set; }
        public bool IsNew { get; set; }
        public bool CanEdit { get; set; }
        public bool IsOwner { get; set; }

        // IWIthAgeModel
        public int Age { get; set; }
        public DateTime BirthDate { get; set; }
    }

    public class QuizzOverviewListResult
    {
        public int TotalCount { get; set; }
        public int PageNum { get; set; }
        public int NumPerPage { get; set; }
        public IList<QuizzOverviewModel> List { get; set; }
    }

    public class QuizzCommentModel : WithAgeModel
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public DateTime PostedDate { get; set; }
        public bool IsDeleted { get; set; }

        // foreign keys
        public int AuthorId { get; set; }
        public int QuizzId { get; set; }

        // generated from query
        public bool IsQuizzmate { get; set; }
        public string AuthorUserName { get; set; }
        public string AuthorFullName { get; set; }
        public string AuthorProfilePixUrl { get; set; }

        public int NumLikes { get; set; }
        public bool IsLiked { get; set; }

        public int NumFlags { get; set; }
        public bool IsFlagged { get; set; }

        // generated by code
        public bool CanEdit { get; set; }
        public bool IsAuthor { get; set; }
        public string AuthorName { get; set; }
    }
}